/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Uptime kontrolü */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Müşteri kaydı */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Giriş */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token'ı iptal et */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        /** Oturumdaki müşteri */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * Vitrinler
         * @description Faz 1'de tek vitrin döner. Dizi biçimi korunur ki ileride vitrin eklenirse
         *     istemciler kırılmasın.
         */
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/menu": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Vitrinin menüsü
         * @description `is_available: false` ürünler yanıtta **kalır** — istemci soluk gösterir,
         *     sepete eklenmesine izin vermez.
         */
        get: operations["getMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * Kendi siparişlerim
         * @description En yeni önce.
         */
        get: operations["listOrders"];
        put?: never;
        /**
         * Sipariş oluştur
         * @description Tutar **sunucuda** hesaplanır. İstemcinin gönderdiği tutar alanları yok sayılır.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Sipariş detayı
         * @description Başkasının siparişi istenirse **`404 NOT_FOUND`** döner — varlık sızdırılmaz
         *     (`403` dönmek siparişin var olduğunu ele verirdi).
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Siparişi iptal et
         * @description Yalnızca `yeni` ve `onaylandi` durumlarında. Sonrasında `422 INVALID_TRANSITION`.
         */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/push-token": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** FCM push token'ı kaydet */
        post: operations["registerPushToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/pair": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cihaz eşleme
         * @description Admin panelden alınan tek kullanımlık kod ile cihaz kaydı. Dönen token süresizdir,
         *     admin panelden iptal edilebilir (sonraki isteklerde `403 DEVICE_REVOKED`).
         */
        post: operations["pairKitchenDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/orders": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * Aktif siparişler
         * @description Varsayılan: `teslim_edildi` ve `iptal` **hariç** bugünün siparişleri.
         *
         *     **Artımlı çekme.** Yanıttaki `max_id` bir sonraki isteğin `after` değeridir;
         *     `server_time` bir sonraki isteğin `since` değeridir. Durum değişimlerini yakalamak
         *     için `since` kullanılmalıdır — `after` yalnızca yeni siparişleri getirir.
         */
        get: operations["listKitchenOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/orders/{id}/status": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Durum ilerlet
         * @description Geçiş matrisi `docs/02-veri-modeli.md` §3'tedir ve **sunucuda** uygulanır.
         *     `yolda` yalnızca `delivery_type=delivery` siparişlerde geçerlidir.
         */
        post: operations["setKitchenOrderStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/orders/{id}/receipt": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Fiş içeriği
         * @description Yazdırma verisini **sunucu** hazırlar; KDS yalnızca ESC/POS'a biçimlendirip basar.
         *     Fiş metninin ne yazacağına dair karar istemcide değildir.
         */
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/print-jobs/{order_id}/ack": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fiş basıldı bildirimi
         * @description Denetim içindir. **İdempotent:** aynı `(order_id, type)` çifti için tekrarlanan
         *     çağrı yeni kayıt açmaz, yine `204` döner. KDS bu çağrı başarısız olursa sessizce
         *     yutar — fişin basılmış olması ack'e bağlı değildir.
         */
        post: operations["ackPrintJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/production-list": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * Üretim listesi
         * @description Aktif siparişlerin (`onaylandi` + `hazirlaniyor`) ürün bazında toplamı.
         *     Çoktan aza sıralıdır.
         */
        get: operations["getProductionList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/busy": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yoğunluk şalteri
         * @description Mutfaktaki tek tuş. Açıkken müşteri arayüzlerinde gecikme uyarısı
         *     çıkar ve admin panelde görünür.
         *
         *     **Sipariş almayı DURDURMAZ.** Siparişi gerçekten kesen şalter
         *     `ordering_enabled`'dır ve yalnızca yönetici değiştirebilir —
         *     mutfak personeli tek tuşla cirosu kapatabilmemeli.
         *
         *     Durum vitrine yazılır, cihaza değil: iki kasa olsa ikisi de aynı
         *     şeyi gösterir ve müşteri tarafı zaten vitrini okur.
         */
        post: operations["setKitchenBusy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kitchen/heartbeat": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * Canlılık bildirimi
         * @description Cihazın `last_seen_at` alanını günceller. 60 saniyede bir gönderilir.
         *     `last_seen_at` 5 dakikadan eskiyse admin panelde uyarı çıkar.
         */
        get: operations["kitchenHeartbeat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app-version": {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * Uygulama sürüm bilgisi
         * @description İstemci sürümü `min_supported` altındaysa zorunlu güncelleme ekranı gösterir.
         */
        get: operations["getAppVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int64
         * @description **Kuruş** cinsinden tam sayı. `4550` = 45,50 TL.
         * @example 4550
         */
        Money: number;
        /** @constant */
        Currency: "TRY";
        /** @example 1.0.0 */
        SemVer: string;
        /**
         * @description Geçiş matrisi (`docs/02-veri-modeli.md` §3):
         *
         *     | Kaynak | İzinli hedefler |
         *     |---|---|
         *     | `yeni` | `onaylandi`, `iptal` |
         *     | `onaylandi` | `hazirlaniyor`, `iptal` |
         *     | `hazirlaniyor` | `hazir`, `iptal` |
         *     | `hazir` | `yolda` (delivery), `teslim_edildi` (pickup), `iptal` |
         *     | `yolda` | `teslim_edildi`, `iptal` |
         *     | `teslim_edildi` | — (terminal) |
         *     | `iptal` | — (terminal) |
         * @enum {string}
         */
        OrderStatus: "yeni" | "onaylandi" | "hazirlaniyor" | "hazir" | "yolda" | "teslim_edildi" | "iptal";
        /** @enum {string} */
        DeliveryType: "delivery" | "pickup";
        /**
         * @description `online` = sanal POS, `cash` = kapıda ödeme, `account` = cari hesap.
         *
         *     Faz 1'de `online`, gerçek tahsilat yapmayan bir **simülasyon**
         *     geçidine bağlıdır; akış gerçek POS ile aynıdır.
         * @enum {string}
         */
        PaymentMethod: "online" | "cash" | "account";
        /**
         * @description Faz 1'de yalnızca bu iki değer üretilir. Sanal POS devreye girdiğinde
         *     `failed`/`refunded` **eklenebilir** (ek değer, kırıcı değişiklik değil);
         *     istemciler bilmedikleri değeri "belirsiz" olarak göstermeli, çökmemelidir.
         * @enum {string}
         */
        PaymentStatus: "pending" | "paid";
        /** @enum {string} */
        ReceiptType: "mutfak" | "musteri";
        /** @enum {string} */
        ErrorCode: "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_FAILED" | "INVALID_TRANSITION" | "LOCATION_CLOSED" | "ITEM_UNAVAILABLE" | "DEVICE_REVOKED" | "RATE_LIMITED" | "SERVER_ERROR";
        /**
         * @description Tüm hataların tek biçimi.
         * @example {
         *       "error": {
         *         "code": "INVALID_TRANSITION",
         *         "message": "Sipariş bu duruma geçirilemez.",
         *         "details": {
         *           "from": "yeni",
         *           "to": "hazir"
         *         }
         *       }
         *     }
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Kullanıcıya gösterilebilir Türkçe metin. */
                message: string;
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
        PaginationMeta: {
            page: number;
            per_page: number;
            total: number;
            last_page: number;
        };
        RegisterRequest: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            /**
             * @description Başında 0 veya +90 olmadan 10 hane.
             * @example 5551234567
             */
            telephone: string;
            /** Format: password */
            password: string;
            /**
             * @description `false` ise `422 VALIDATION_FAILED`. Onay zaman damgasıyla saklanır.
             * @constant
             */
            kvkk_accepted: true;
        };
        AuthResponse: {
            token: string;
            customer: {
                /** Format: int64 */
                id: number;
                first_name: string;
            };
        };
        Customer: {
            /** Format: int64 */
            id: number;
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            telephone: string;
            /** Format: int64 */
            default_location_id?: number | null;
        };
        Location: {
            /** Format: int64 */
            id: number;
            name: string;
            slug: string;
            /** @description Çalışma saatlerinden **türetilir**. Şu an sipariş saati içinde miyiz? */
            is_open: boolean;
            /**
             * @description Yöneticinin admin panelden çevirdiği elle ana şalter. `false` ise saat uygun
             *     olsa bile sipariş alınmaz.
             */
            ordering_enabled: boolean;
            /**
             * @description Günlük son sipariş saati (Europe/Istanbul) veya `null`.
             * @example 16:00
             */
            order_cutoff?: string | null;
            /** @description Altında sipariş `422 VALIDATION_FAILED`. */
            min_order_total: components["schemas"]["Money"];
            /**
             * @description `delivery_type=delivery` siparişlere eklenecek sabit teslimat
             *     ücreti; gel-al siparişte uygulanmaz.
             *
             *     **Neden sözleşmede:** bu alan olmadan istemci, kullanıcıya
             *     siparişi onaylatmadan önce **toplam tutarı gösteremiyordu** —
             *     yalnızca ara toplamı gösterip "teslimat sipariş adımında
             *     hesaplanır" demek zorunda kalıyordu. Mesafeli satışta ödenecek
             *     tutarın onaydan önce görünmesi gerekir.
             *
             *     Gösterim içindir; **bağlayıcı olan sunucunun hesabıdır**
             *     (`OrderDetail.delivery_fee`). İkisi ayrışırsa sunucu haklıdır.
             */
            delivery_fee: components["schemas"]["Money"];
            /**
             * @description Bu vitrinde **açık** olan ödeme yöntemleri. İstemci ödeme ekranında yalnızca
             *     bunları gösterir. Listede olmayan yöntemle sipariş → `422 VALIDATION_FAILED`.
             */
            payment_methods: components["schemas"]["PaymentMethod"][];
            /**
             * @description Mutfak yoğun mu? Mutfak ekranındaki tek tuşla açılır
             *     (`POST /kitchen/busy`).
             *
             *     **Sipariş almayı ENGELLEMEZ.** İstemci yalnızca `busy_message`
             *     uyarısını gösterir. Siparişi gerçekten kesen şalter
             *     `ordering_enabled`'dır ve o yöneticinindir.
             */
            busy?: boolean;
            /**
             * @description `busy` doğruyken gösterilecek metin. Yönetici admin panelden
             *     değiştirebilir. İstemciler kendi metnini gömmemelidir: metin
             *     değişince üç uygulamayı birden yayınlamak gerekirdi.
             * @example Mutfağımız şu anda yoğun. Siparişiniz alınır ancak hazırlanması normalden uzun sürebilir.
             */
            busy_message?: string;
        };
        MenuCategory: {
            /** Format: int64 */
            id: number;
            name: string;
            sort: number;
            items: components["schemas"]["MenuItem"][];
        };
        MenuItem: {
            /** Format: int64 */
            id: number;
            name: string;
            description?: string | null;
            price: components["schemas"]["Money"];
            currency: components["schemas"]["Currency"];
            /** Format: uri */
            image_url?: string | null;
            /** @description `false` ürün yanıtta kalır; istemci soluk gösterir, sepete eklemez. */
            is_available: boolean;
            allergens?: string[];
            options?: components["schemas"]["MenuOption"][];
        };
        MenuOption: {
            /** Format: int64 */
            id: number;
            name: string;
            /**
             * @description Bilinen değerler: `radio` (tek seçim), `checkbox` (çok seçim), `select`.
             *     Kapalı enum değildir — TastyIgniter'ın gerçek değer kümesi `B-02`'de
             *     doğrulanacak (bkz. BILINMEYENLER). İstemci bilinmeyen tipi `radio` gibi ele alır.
             * @example radio
             */
            type: string;
            required: boolean;
            values: components["schemas"]["MenuOptionValue"][];
        };
        MenuOptionValue: {
            /** Format: int64 */
            id: number;
            name: string;
            /**
             * Format: int64
             * @description Kuruş cinsinden **işaretli** fark; negatif olabilir.
             */
            price_delta: number;
        };
        Address: {
            line1: string;
            district: string;
            city: string;
            note?: string | null;
        };
        OrderCreateRequest: {
            /** Format: int64 */
            location_id: number;
            items: {
                /** Format: int64 */
                menu_id: number;
                quantity: number;
                option_value_ids?: number[];
                note?: string | null;
            }[];
            delivery_type: components["schemas"]["DeliveryType"];
            /** @description `delivery` ise zorunlu, `pickup` ise yok sayılır. */
            address?: components["schemas"]["Address"] | null;
            /**
             * Format: date-time
             * @description İstenen teslim zamanı. `order_cutoff` kuralına takılırsa `LOCATION_CLOSED`.
             */
            requested_at?: string | null;
            payment_method: components["schemas"]["PaymentMethod"];
            customer_note?: string | null;
        };
        Payment: {
            method: components["schemas"]["PaymentMethod"];
            status: components["schemas"]["PaymentStatus"];
            /**
             * Format: uri
             * @description Yalnızca `online` yönteminde ve sipariş **henüz ödenmemişken**
             *     dolu; istemci kullanıcıyı buraya yönlendirir. Ödendikten sonra
             *     `null` döner — kullanıcı ikinci kez ödeme sayfasına
             *     gönderilmemelidir.
             *
             *     Faz 1'de bu adres bir **simülasyon** sayfasıdır (gerçek tahsilat
             *     yok). Akış gerçek sanal POS ile birebir aynıdır; sağlayıcı
             *     devreye girdiğinde yalnızca adresin işaret ettiği sayfa değişir.
             */
            redirect_url?: string | null;
        };
        OrderCreated: {
            /** Format: int64 */
            id: number;
            /** @example S-5012 */
            order_number: string;
            status: components["schemas"]["OrderStatus"];
            total: components["schemas"]["Money"];
            currency: components["schemas"]["Currency"];
            payment: components["schemas"]["Payment"];
            /** Format: date-time */
            created_at: string;
        };
        OrderSummary: {
            /** Format: int64 */
            id: number;
            order_number: string;
            status: components["schemas"]["OrderStatus"];
            total: components["schemas"]["Money"];
            currency: components["schemas"]["Currency"];
            item_count: number;
            /** Format: date-time */
            created_at: string;
        };
        OrderItem: {
            /** Format: int64 */
            menu_id: number;
            name: string;
            quantity: number;
            options?: string[];
            note?: string | null;
            /** @description Seçenek farkları **dahil** birim fiyat. */
            unit_price: components["schemas"]["Money"];
            line_total: components["schemas"]["Money"];
        };
        StatusHistoryEntry: {
            status: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            at: string;
        };
        OrderDetail: {
            /** Format: int64 */
            id: number;
            order_number: string;
            status: components["schemas"]["OrderStatus"];
            items: components["schemas"]["OrderItem"][];
            subtotal: components["schemas"]["Money"];
            /** @description `pickup` siparişte her zaman `0`. */
            delivery_fee: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
            currency: components["schemas"]["Currency"];
            delivery_type: components["schemas"]["DeliveryType"];
            /** @description `pickup` siparişte `null`. */
            address?: components["schemas"]["Address"] | null;
            /** Format: date-time */
            requested_at?: string | null;
            customer_note?: string | null;
            payment: components["schemas"]["Payment"];
            status_history: components["schemas"]["StatusHistoryEntry"][];
            /** Format: date-time */
            created_at: string;
        };
        /** @description Fiyat alanı **yoktur** — mutfak kapsamı fiyat görmez. */
        KitchenOrderItem: {
            name: string;
            quantity: number;
            options?: string[];
            note?: string | null;
        };
        /**
         * @description Fiyat, telefon, adres ve e-posta **içermez**. `customer_label` yalnızca
         *     ad + soyad baş harfidir.
         */
        KitchenOrder: {
            /** Format: int64 */
            id: number;
            order_number: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            requested_at?: string | null;
            delivery_type: components["schemas"]["DeliveryType"];
            /** @example Ayşe Y. */
            customer_label?: string | null;
            items: components["schemas"]["KitchenOrderItem"][];
            customer_note?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReceiptLine: {
            quantity: number;
            name: string;
            options?: string[];
            note?: string | null;
        };
        KitchenReceipt: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mutfak";
            order_number: string;
            delivery_type: components["schemas"]["DeliveryType"];
            /** Format: date-time */
            requested_at?: string | null;
            lines: components["schemas"]["ReceiptLine"][];
            customer_note?: string | null;
            /** Format: date-time */
            printed_at?: string | null;
        };
        CustomerReceipt: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "musteri";
            order_number: string;
            delivery_type: components["schemas"]["DeliveryType"];
            /** Format: date-time */
            requested_at?: string | null;
            items: components["schemas"]["OrderItem"][];
            subtotal: components["schemas"]["Money"];
            delivery_fee: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
            currency: components["schemas"]["Currency"];
            payment: components["schemas"]["Payment"];
            /**
             * @description `delivery` siparişte dolu. Mutfak kapsamının müşteri adresini gördüğü
             *     **tek** yer burasıdır.
             */
            address?: components["schemas"]["Address"] | null;
            customer_label?: string | null;
            /** Format: date-time */
            printed_at?: string | null;
        };
    };
    responses: {
        /** @description Token yok veya geçersiz (`UNAUTHENTICATED`) */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Kapsam yetersiz (`FORBIDDEN`) veya cihaz iptal edilmiş (`DEVICE_REVOKED`) */
        ForbiddenOrRevoked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Kayıt yok (`NOT_FOUND`) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Alan doğrulama hatası (`VALIDATION_FAILED`); `details` alan bazlıdır */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Geçersiz durum geçişi (`INVALID_TRANSITION`) */
        InvalidTransition: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Çok fazla istek (`RATE_LIMITED`) */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        AppId: "website" | "musteriapp" | "mutfakapp";
        AppVersion: components["schemas"]["SemVer"];
        AcceptLanguage: string;
        Page: number;
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaMoney = components['schemas']['Money'];
export type SchemaCurrency = components['schemas']['Currency'];
export type SchemaSemVer = components['schemas']['SemVer'];
export type SchemaOrderStatus = components['schemas']['OrderStatus'];
export type SchemaDeliveryType = components['schemas']['DeliveryType'];
export type SchemaPaymentMethod = components['schemas']['PaymentMethod'];
export type SchemaPaymentStatus = components['schemas']['PaymentStatus'];
export type SchemaReceiptType = components['schemas']['ReceiptType'];
export type SchemaErrorCode = components['schemas']['ErrorCode'];
export type SchemaError = components['schemas']['Error'];
export type SchemaPaginationMeta = components['schemas']['PaginationMeta'];
export type SchemaRegisterRequest = components['schemas']['RegisterRequest'];
export type SchemaAuthResponse = components['schemas']['AuthResponse'];
export type SchemaCustomer = components['schemas']['Customer'];
export type SchemaLocation = components['schemas']['Location'];
export type SchemaMenuCategory = components['schemas']['MenuCategory'];
export type SchemaMenuItem = components['schemas']['MenuItem'];
export type SchemaMenuOption = components['schemas']['MenuOption'];
export type SchemaMenuOptionValue = components['schemas']['MenuOptionValue'];
export type SchemaAddress = components['schemas']['Address'];
export type SchemaOrderCreateRequest = components['schemas']['OrderCreateRequest'];
export type SchemaPayment = components['schemas']['Payment'];
export type SchemaOrderCreated = components['schemas']['OrderCreated'];
export type SchemaOrderSummary = components['schemas']['OrderSummary'];
export type SchemaOrderItem = components['schemas']['OrderItem'];
export type SchemaStatusHistoryEntry = components['schemas']['StatusHistoryEntry'];
export type SchemaOrderDetail = components['schemas']['OrderDetail'];
export type SchemaKitchenOrderItem = components['schemas']['KitchenOrderItem'];
export type SchemaKitchenOrder = components['schemas']['KitchenOrder'];
export type SchemaReceiptLine = components['schemas']['ReceiptLine'];
export type SchemaKitchenReceipt = components['schemas']['KitchenReceipt'];
export type SchemaCustomerReceipt = components['schemas']['CustomerReceipt'];
export type ResponseUnauthenticated = components['responses']['Unauthenticated'];
export type ResponseForbiddenOrRevoked = components['responses']['ForbiddenOrRevoked'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponseValidationFailed = components['responses']['ValidationFailed'];
export type ResponseInvalidTransition = components['responses']['InvalidTransition'];
export type ResponseRateLimited = components['responses']['RateLimited'];
export type ParameterAppId = components['parameters']['AppId'];
export type ParameterAppVersion = components['parameters']['AppVersion'];
export type ParameterAcceptLanguage = components['parameters']['AcceptLanguage'];
export type ParameterPage = components['parameters']['Page'];
export type ParameterPerPage = components['parameters']['PerPage'];
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ayakta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        /** Format: date-time */
                        server_time: string;
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Hesap oluştu */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Giriş başarılı */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Çıkış yapıldı */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Müşteri profili */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listLocations: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vitrin listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Location"][];
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getMenu: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kategoriler ve ürünler */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MenuCategory"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sipariş listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrderSummary"][];
                        meta: components["schemas"]["PaginationMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            /** @description Sipariş oluştu */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCreated"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            /**
             * @description Doğrulama hatası. Olası kodlar: `VALIDATION_FAILED`, `LOCATION_CLOSED`,
             *     `ITEM_UNAVAILABLE`.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sipariş */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Güncel sipariş */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidTransition"];
        };
    };
    registerPushToken: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    fcm_token: string;
                    /** @enum {string} */
                    platform: "android";
                };
            };
        };
        responses: {
            /** @description Kaydedildi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    pairKitchenDevice: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example K7X2-9QMD */
                    pairing_code: string;
                    device_name: string;
                };
            };
        };
        responses: {
            /** @description Eşleme başarılı */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        device_id: number;
                        token: string;
                        /** Format: date-time */
                        server_time: string;
                    };
                };
            };
            /** @description Kod geçersiz veya süresi dolmuş */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listKitchenOrders: {
        parameters: {
            query?: {
                /** @description Bu sipariş kimliğinden büyükleri getir (yalnızca yeni siparişler). */
                after?: number;
                /** @description Bu zaman damgasından sonra **güncellenenleri** getir. */
                since?: string;
                /** @description `true` ise bugünün tamamlananları da gelir. */
                include_completed?: boolean;
            };
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sipariş listesi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KitchenOrder"][];
                        /**
                         * Format: date-time
                         * @description Bir sonraki `since` değeri.
                         */
                        server_time: string;
                        /**
                         * Format: int64
                         * @description Bir sonraki `after` değeri. Liste boşsa önceki değer korunur.
                         */
                        max_id: number;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrRevoked"];
        };
    };
    setKitchenOrderStatus: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["OrderStatus"];
                };
            };
        };
        responses: {
            /** @description Güncel sipariş özeti */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KitchenOrder"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrRevoked"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidTransition"];
        };
    };
    getReceipt: {
        parameters: {
            query: {
                type: components["schemas"]["ReceiptType"];
            };
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fiş verisi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KitchenReceipt"] | components["schemas"]["CustomerReceipt"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrRevoked"];
            404: components["responses"]["NotFound"];
        };
    };
    ackPrintJob: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type: components["schemas"]["ReceiptType"];
                    /** Format: date-time */
                    printed_at: string;
                };
            };
        };
        responses: {
            /** @description Kaydedildi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrRevoked"];
            404: components["responses"]["NotFound"];
        };
    };
    getProductionList: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ürün toplamları */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: int64 */
                            menu_id: number;
                            name: string;
                            total: number;
                        }[];
                        /** Format: date-time */
                        as_of: string;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrRevoked"];
        };
    };
    setKitchenBusy: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    busy: boolean;
                };
            };
        };
        responses: {
            /** @description Yeni durum */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        busy: boolean;
                        busy_message: string;
                        /** Format: date-time */
                        server_time: string;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrRevoked"];
            /** @description Doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    kitchenHeartbeat: {
        parameters: {
            query?: never;
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sunucu bilgisi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        server_time: string;
                        min_supported_version: components["schemas"]["SemVer"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrRevoked"];
        };
    };
    getAppVersion: {
        parameters: {
            query: {
                app_id: "musteriapp" | "mutfakapp";
            };
            header: {
                "X-App-Id": components["parameters"]["AppId"];
                "X-App-Version": components["parameters"]["AppVersion"];
                "Accept-Language": components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sürüm bilgisi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        app_id: "musteriapp" | "mutfakapp";
                        latest: components["schemas"]["SemVer"];
                        min_supported: components["schemas"]["SemVer"];
                        /**
                         * Format: uri
                         * @description Yalnızca `mutfakapp` için dolu (`.deb` adresi).
                         */
                        download_url?: string | null;
                        notes?: string | null;
                    };
                };
            };
            /**
             * @description `app_id` eksik veya enum dışı. Geçersiz enum bir **doğrulama**
             *     hatasıdır, "kayıt yok" değil — mock ile sunucu bu noktada
             *     ayrışmıştı, sözleşme 422'de netleştirildi.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
